version: "3"
services:
  tcp_server:
    container_name: tcp_server
    build:
      context: ./
      dockerfile: ./Dockerfile-server
    env_file:
      - var.env
  tcp_client:
    depends_on:
      - "tcp_server"
    container_name: tcp_client
    build:
      context: ./
      dockerfile: ./Dockerfile-client
    env_file:
      - var.env